package com.example.ticket_manager.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.ticket_manager.domain.ConcertStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@AllArgsConstructor
@NoArgsConstructor
@Builder
@Data
@DynamoDBTable(tableName = "concert")
public class Concert {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String concertId;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private String artist;
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "availabilityStatus-date-index")
    private Date date;
    @DynamoDBAttribute
    private String venue;
    @DynamoDBAttribute
    private int totalSeats;
    @DynamoDBAttribute
    private int soldSeats;
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "availabilityStatus-date-index")
    @DynamoDBTypeConvertedEnum
    private ConcertStatus availabilityStatus;
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date createdAt;
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    private Date updatedAt;

    public int availableSeats() {
        return totalSeats - soldSeats;
    }
}
